package com.smartinstitute.erp.audit.entity;

import com.smartinstitute.erp.audit.enums.AuditAction;
import com.smartinstitute.erp.common.entity.BaseEntity;
import com.smartinstitute.erp.institute.entity.Institute;
import com.smartinstitute.erp.user.entity.User;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.util.Map;

/**
 * Represents an audit record generated by the ERP application.
 *
 * <p>
 * Audit records provide a historical trail of important business
 * and security-related operations performed by users or the system.
 * </p>
 *
 * <p>
 * Each audit record belongs to an institute so that audit information
 * remains isolated in the multi-tenant ERP architecture.
 * </p>
 *
 * <p>
 * The old and new values are stored as PostgreSQL JSONB data.
 * This allows the audit module to capture changes without creating
 * separate audit tables for every ERP entity.
 * </p>
 */
@Entity
@Table(
        name = "audit_logs",
        indexes = {

                /**
                 * Supports institute-level audit searches.
                 */
                @Index(
                        name = "idx_audit_log_institute",
                        columnList = "institute_id"
                ),

                /**
                 * Supports finding actions performed by a particular user.
                 */
                @Index(
                        name = "idx_audit_log_user",
                        columnList = "user_id"
                ),

                /**
                 * Supports filtering audit records by action.
                 */
                @Index(
                        name = "idx_audit_log_action",
                        columnList = "action"
                ),

                /**
                 * Supports retrieving the history of a particular
                 * business entity.
                 */
                @Index(
                        name = "idx_audit_log_entity",
                        columnList = "entity_type,entity_id"
                ),

                /**
                 * Supports chronological audit queries.
                 */
                @Index(
                        name = "idx_audit_log_created_at",
                        columnList = "created_at"
                ),

                /**
                 * Common query pattern for a tenant:
                 *
                 * WHERE institute_id = ?
                 * ORDER BY created_at DESC
                 */
                @Index(
                        name = "idx_audit_log_institute_created",
                        columnList = "institute_id,created_at"
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AuditLog extends BaseEntity {

    /**
     * Institute to which this audit record belongs.
     *
     * <p>
     * This field is mandatory because the ERP is multi-tenant.
     * Audit records must never be shared between institutes.
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "institute_id",
            nullable = false
    )
    private Institute institute;

    /**
     * User who performed the action.
     *
     * <p>
     * This allows administrators to determine which user
     * performed a particular operation.
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "user_id"
    )
    private User user;

    /**
     * Type of action performed.
     *
     * <p>
     * Stored as a string instead of an ordinal value so that
     * changing enum ordering does not corrupt historical data.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(
            nullable = false,
            length = 50
    )
    private AuditAction action;

    /**
     * Type of business entity affected by the operation.
     *
     * <p>
     * Examples:
     * STUDENT, COURSE, BATCH, STUDENT_FEE, ATTENDANCE, USER.
     * </p>
     */
    @Column(
            name = "entity_type",
            nullable = false,
            length = 100
    )
    private String entityType;

    /**
     * ID of the business entity affected by the operation.
     *
     * <p>
     * This is intentionally stored as a generic Long because
     * different ERP entities can be audited through the same
     * audit table.
     * </p>
     */
    @Column(
            name = "entity_id"
    )
    private Long entityId;

    /**
     * Human-readable description of the audited operation.
     *
     * <p>
     * Example:
     *
     * "Student fee updated successfully."
     * </p>
     */
    @Column(
            length = 1000
    )
    private String description;

    /**
     * Previous state of the entity before the operation.
     *
     * <p>
     * Stored as PostgreSQL JSONB so different entities can have
     * different structures without requiring separate audit tables.
     * </p>
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(
            name = "old_value",
            columnDefinition = "jsonb"
    )
    private Map<String, Object> oldValue;

    /**
     * New state of the entity after the operation.
     *
     * <p>
     * Stored as PostgreSQL JSONB.
     * </p>
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(
            name = "new_value",
            columnDefinition = "jsonb"
    )
    private Map<String, Object> newValue;

    /**
     * IP address from which the operation was performed.
     *
     * <p>
     * Useful during security investigations and suspicious
     * activity analysis.
     * </p>
     */
    @Column(
            name = "ip_address",
            length = 100
    )
    private String ipAddress;

    /**
     * User-Agent header of the client that performed the operation.
     *
     * <p>
     * This can help identify the browser, operating system or
     * client application involved in the request.
     * </p>
     */
    @Column(
            name = "user_agent",
            length = 500
    )
    private String userAgent;
}