package com.smartinstitute.erp.audit.dto.request;

import com.smartinstitute.erp.audit.enums.AuditAction;
import com.smartinstitute.erp.common.enums.SortDirection;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Request filters for searching audit history.
 *
 * <p>
 * All filters are optional. Audit records are always restricted
 * to the currently logged-in user's institute.
 * </p>
 */
@Getter
@Setter
public class AuditLogSearchRequest {

    /**
     * Optional user filter.
     *
     * <p>
     * When provided, only audit records generated by the specified
     * user are included.
     * </p>
     */
    private Long userId;

    /**
     * Optional audit action filter.
     *
     * <p>
     * Examples include CREATE, UPDATE, DELETE and LOGIN.
     * </p>
     */
    private AuditAction action;

    /**
     * Optional affected entity type filter.
     *
     * <p>
     * Example values:
     * STUDENT, COURSE, BATCH, STUDENT_FEE.
     * </p>
     */
    private String entityType;

    /**
     * Optional affected entity identifier filter.
     */
    private Long entityId;

    /**
     * Optional start date and time.
     *
     * <p>
     * Audit records created before this date/time are excluded.
     * </p>
     */
    private LocalDateTime dateFrom;

    /**
     * Optional end date and time.
     *
     * <p>
     * Audit records created after this date/time are excluded.
     * </p>
     */
    private LocalDateTime dateTo;

    /**
     * Zero-based page number.
     */
    @Min(0)
    private Integer page = 0;

    /**
     * Number of audit records per page.
     */
    @Min(1)
    @Max(100)
    private Integer size = 10;

    /**
     * Field used for sorting.
     *
     * <p>
     * The service validates this value against the audit
     * sortable-fields whitelist.
     * </p>
     */
    private String sortBy = "createdAt";

    /**
     * Sort direction.
     *
     * <p>
     * Supported values are ASC and DESC.
     * </p>
     */
    private SortDirection sortDirection = SortDirection.DESC;
}