spring:
  application:
    name: smart-institute-erp

  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO