spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_institute_erp
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

server:
  error:
    include-message: never